# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def IsEven(val):
    if(val % 2) == 0:
       return True
    else:
       return False

def FindSumOfEvenFibonacciNumbers(Terms):
    counter = 0
    number1, number2 = 0, 1
    values = []
    # loop to find the all the fibonacci numbers by the terms.
    while True:
          current = number1 + number2
          number1 = number2
          number2 = current
          if (current <= Terms):
              if IsEven(current):
                 values.append(current)
          else:
              break
    return sum(values)

Terms = 4000000
print("FindSumOfEvenFibonacciNumbers for {} terms is {}".format(Terms, FindSumOfEvenFibonacciNumbers(Terms)))
